# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=75)),
                ('definition', models.CharField(max_length=512)),
            ],
        ),
    ]
