# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_todayword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todayword',
            name='word',
        ),
        migrations.DeleteModel(
            name='TodayWord',
        ),
    ]
