# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0004_todayword'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='author',
            field=models.CharField(default='everydayword.ru', max_length=128),
        ),
    ]
