# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0005_dictionary_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
