# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0006_dictionary_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_example', models.CharField(max_length=1024)),
            ],
        ),
    ]
