# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0007_useexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='useexample',
            name='dictionary_word',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dict.Dictionary'),
        ),
    ]
