# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0008_useexample_dictionary_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useexample',
            name='dictionary_word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dict.Dictionary'),
        ),
    ]
