# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0009_auto_20161109_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useexample',
            old_name='dictionary_word',
            new_name='word',
        ),
    ]
