# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0012_auto_20161110_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
